//! Model limits lookup. Cascade: live models-cache (harvested from the
//! provider's `/v1/models`) → embedded models.dev snapshot
//! (`src/data/model_limits.json`, regenerated by the providers-sync skill)
//! → none. `/v1/models` stays authoritative when it carries the field.

use std::collections::HashMap;
use std::sync::LazyLock;
use std::sync::atomic::{AtomicU64, Ordering};

use serde::Deserialize;

use super::model_names::strip_context_suffix;
use super::models_cache::{ModelsCache, full_catalog_key};

#[derive(Debug, Clone, PartialEq)]
pub struct ModelLimits {
    pub context: Option<u64>,
    pub output: Option<u64>,
    pub tool_call: bool,
    pub reasoning: bool,
    pub attachment: bool,
    pub image_input: bool,
    /// Model emits images in its output (`g` snapshot flag).
    pub image_output: bool,
    /// False when the model rejects the `temperature` param (o-series,
    /// forced-reasoning claude variants).
    pub temperature: bool,
    pub deprecated: bool,
    /// Supported reasoning-effort values as published (may include levels
    /// like `xhigh`/`max` — consumers filter to what their tool accepts).
    pub reasoning_efforts: Vec<String>,
    /// USD-per-1M-token prices, when models.dev lists them.
    pub pricing: Option<Pricing>,
}

/// USD per 1M tokens. `cache_read`/`cache_write` fall back to `input` when unlisted.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Pricing {
    pub input: Option<f64>,
    pub output: Option<f64>,
    pub cache_read: Option<f64>,
    pub cache_write: Option<f64>,
}

impl Pricing {
    /// Estimated USD for a usage split (cache ⊂ prompt, the `SessionTokens`
    /// convention); `None` without both input and output prices.
    pub fn cost_usd(&self, t: &crate::services::session_store::SessionTokens) -> Option<f64> {
        let (input, output) = (self.input?, self.output?);
        let per = 1e-6;
        let base_in = t
            .prompt_tokens
            .saturating_sub(t.cache_read_tokens)
            .saturating_sub(t.cache_write_tokens) as f64;
        Some(
            base_in * input * per
                + t.cache_read_tokens as f64 * self.cache_read.unwrap_or(input) * per
                + t.cache_write_tokens as f64 * self.cache_write.unwrap_or(input) * per
                + t.completion_tokens as f64 * output * per,
        )
    }

    fn known_fields(&self) -> usize {
        [self.input, self.output, self.cache_read, self.cache_write]
            .iter()
            .filter(|v| v.is_some())
            .count()
    }
}

/// Prices for `model` from the embedded snapshot (same folded lookup as limits).
pub fn model_pricing(model: &str) -> Option<Pricing> {
    snapshot_limits(model)?.pricing
}

/// Snapshot `g` flag. Unknown models → false: the image-gen picker offers only
/// models known to generate.
pub fn model_generates_images(model: &str) -> bool {
    snapshot_limits(model).is_some_and(|l| l.image_output)
}

/// Snapshot `t` flag. Unknown models → false; callers pair this with a
/// snapshot-known predicate (e.g. `model_generates_images`) so the false
/// default never penalizes off-catalog models.
pub fn model_calls_tools(model: &str) -> bool {
    snapshot_limits(model).is_some_and(|l| l.tool_call)
}

/// Cascade result: per-field merge of live cache over snapshot. `caps` are
/// snapshot-only (the cache doesn't store capability flags).
#[derive(Debug, Clone, Default)]
pub struct ResolvedLimits {
    pub context: Option<u64>,
    pub output: Option<u64>,
    pub caps: Option<&'static ModelLimits>,
    /// Reasoning-effort levels (live catalog, else snapshot). Owned, not on
    /// `caps`, since the live source isn't `'static`.
    pub reasoning_efforts: Vec<String>,
}

/// `[context, output, flags, efforts]` + optional `[in, out, cache_read, cache_write]`
/// USD-per-1M prices — see `sync_model_limits.py` (`model_data_sync.rs` writes 4-slot).
type LimitRow = Vec<serde_json::Value>;

#[derive(Deserialize)]
struct SnapshotFile {
    // BTreeMap: sorted iteration keeps fold-collision resolution deterministic.
    models: std::collections::BTreeMap<String, LimitRow>,
}

/// Keys folded (lowercase, `.`→`-`) so dot/dash version spellings match
/// (`claude-sonnet-4.6` ↔ `claude-sonnet-4-6`). Collisions keep the larger
/// context. The embedded snapshot is the floor; the user override written by
/// `aivo update --sync-model-data` is overlaid on top, winning per id.
static SNAPSHOT: LazyLock<HashMap<String, ModelLimits>> = LazyLock::new(build_snapshot);

fn build_snapshot() -> HashMap<String, ModelLimits> {
    let embedded = embedded_rows();
    // Tests skip the overlay so assertions don't depend on the dev's real
    // `~/.config/aivo`.
    if !cfg!(test)
        && let Some(over) = load_override_rows()
    {
        return overlay_override(embedded, over);
    }
    fold_rows(embedded)
}

fn embedded_rows() -> std::collections::BTreeMap<String, LimitRow> {
    let parsed: SnapshotFile =
        serde_json::from_str(crate::services::embedded_assets::model_limits_json())
            .expect("embedded model_limits.json is valid");
    parsed.models
}

/// Best-effort: a missing, corrupt, or future-format file yields `None` (the
/// embedded floor stands). Never panics — a bad file must not brick lookups.
fn load_override_rows() -> Option<std::collections::BTreeMap<String, LimitRow>> {
    let path = override_model_limits_path()?;
    let text = std::fs::read_to_string(&path).ok()?;
    let parsed: SnapshotFile = serde_json::from_str(&text).ok()?;
    (!parsed.models.is_empty()).then_some(parsed.models)
}

/// Overlay `over` onto `base` so the override wins per *folded* id. Each source
/// is folded independently before overlaying: merging raw keys then folding
/// would route both through `fold_rows`' larger-context tiebreak, letting a
/// stale embedded entry under a fold-equivalent spelling (`claude-sonnet-4.6`
/// vs `claude-sonnet-4-6`) beat a fresh — possibly smaller — override value.
fn overlay_override(
    base: std::collections::BTreeMap<String, LimitRow>,
    over: std::collections::BTreeMap<String, LimitRow>,
) -> HashMap<String, ModelLimits> {
    let mut map = fold_rows(base);
    // Override wins per folded id; a price-less override row (the 4-slot shape
    // `model_data_sync` writes) keeps the embedded pricing rather than erasing it.
    for (k, mut limits) in fold_rows(over) {
        if let Some(prev) = map.get(&k) {
            merge_pricing(&mut limits, prev.pricing);
            // The `g` flag postdates deployed override caches (2026-08): a row
            // written by an older binary would otherwise mask a capability the
            // embedded snapshot knows — until the user happens to resync.
            limits.image_output |= prev.image_output;
        }
        map.insert(k, limits);
    }
    map
}

fn fold_rows(rows: std::collections::BTreeMap<String, LimitRow>) -> HashMap<String, ModelLimits> {
    let mut map: HashMap<String, ModelLimits> = HashMap::with_capacity(rows.len());
    for (id, row) in rows {
        let Some(mut limits) = parse_row(&row) else {
            continue;
        };
        let key = fold(&id);
        // Corrects stale override caches too, not just the embedded data.
        if gpt_rejects_effort_minimal(&key) {
            limits.reasoning_efforts.retain(|e| e != "minimal");
        }
        match map.get_mut(&key) {
            Some(prev) if prev.context.unwrap_or(0) >= limits.context.unwrap_or(0) => {
                // The loser may know prices the winner lacks — a zero-priced
                // ':free' pool must not shadow the vendor's list price.
                merge_pricing(prev, limits.pricing);
                prev.temperature &= limits.temperature;
            }
            Some(prev) => {
                let keep = prev.pricing;
                let fixed_temp = !prev.temperature;
                *prev = limits;
                merge_pricing(prev, keep);
                // Sampling params 400 on models that reject them, while omitting
                // them is harmless — so on a fold collision (`gpt-5.4` vs
                // `gpt-5-4`) the restrictive spelling wins regardless of which
                // side the context tie-break picked.
                prev.temperature &= !fixed_temp;
            }
            None => {
                map.insert(key, limits);
            }
        }
    }
    map
}

/// Fill `limits.pricing` from `other` when absent or less complete.
fn merge_pricing(limits: &mut ModelLimits, other: Option<Pricing>) {
    let Some(other) = other else { return };
    match &limits.pricing {
        Some(own) if own.known_fields() >= other.known_fields() => {}
        _ => limits.pricing = Some(other),
    }
}

/// Parse one snapshot row; `None` on a malformed row (skipped, never panics).
fn parse_row(row: &[serde_json::Value]) -> Option<ModelLimits> {
    if row.len() < 4 {
        return None;
    }
    let context = row[0].as_u64();
    let output = row[1].as_u64();
    let flags = row[2].as_str()?;
    let efforts = row[3].as_str()?;
    let price = |i: usize| row.get(i).and_then(serde_json::Value::as_f64);
    let pricing = Pricing {
        input: price(4),
        output: price(5),
        cache_read: price(6),
        cache_write: price(7),
    };
    Some(ModelLimits {
        context,
        output,
        tool_call: flags.contains('t'),
        reasoning: flags.contains('r'),
        attachment: flags.contains('a'),
        image_input: flags.contains('i'),
        image_output: flags.contains('g'),
        temperature: !flags.contains('f'),
        deprecated: flags.contains('d'),
        reasoning_efforts: efforts
            .split(',')
            .filter(|s| !s.is_empty())
            .map(str::to_string)
            .collect(),
        pricing: (pricing.known_fields() > 0).then_some(pricing),
    })
}

/// Path of the user-refreshed snapshot (`<config>/cache/model_limits.json`).
/// Written by `aivo update --sync-model-data`, overlaid by the loader above.
pub fn override_model_limits_path() -> Option<std::path::PathBuf> {
    Some(crate::services::paths::model_limits(
        &crate::services::paths::config_dir(),
    ))
}

/// Folded keys sorted longest-first so the substring fallback picks the most
/// specific entry; keys < 6 chars excluded to avoid false hits (`o1`, `gpt-4`).
static KEYS_LONGEST_FIRST: LazyLock<Vec<&'static str>> = LazyLock::new(|| {
    let snapshot: &'static HashMap<String, ModelLimits> = &SNAPSHOT;
    let mut keys: Vec<&'static str> = snapshot
        .keys()
        .map(String::as_str)
        .filter(|k| k.len() >= 6)
        .collect();
    keys.sort_by(|a, b| b.len().cmp(&a.len()).then(a.cmp(b)));
    keys
});

fn fold(s: &str) -> String {
    s.trim().to_ascii_lowercase().replace('.', "-")
}

fn strip_date_suffix(s: &str) -> Option<&str> {
    let (base, suffix) = s.rsplit_once('-')?;
    (suffix.len() == 8 && suffix.chars().all(|c| c.is_ascii_digit())).then_some(base)
}

/// Snapshot-only lookup. Match order: exact (folded) → last `/`-segment →
/// `:variant` stripped (`:free`, bedrock `:0`) → `-YYYYMMDD` stripped →
/// longest-key substring (covers `us.anthropic.…` ids).
pub fn snapshot_limits(model: &str) -> Option<&'static ModelLimits> {
    let snapshot: &'static HashMap<String, ModelLimits> = &SNAPSHOT;
    let needle = fold(strip_context_suffix(model));
    if needle.is_empty() {
        return None;
    }
    if let Some(hit) = snapshot.get(&needle) {
        return Some(hit);
    }
    let segment = needle.rsplit('/').next().unwrap_or(&needle);
    if let Some(hit) = snapshot.get(segment) {
        return Some(hit);
    }
    let base = segment.split(':').next().unwrap_or(segment);
    if base != segment
        && let Some(hit) = snapshot.get(base)
    {
        return Some(hit);
    }
    if let Some(dateless) = strip_date_suffix(base)
        && let Some(hit) = snapshot.get(dateless)
    {
        return Some(hit);
    }
    KEYS_LONGEST_FIRST
        .iter()
        .find(|key| needle.contains(*key))
        .map(|key| &snapshot[*key])
}

/// True when the snapshot says `model` rejects the `temperature` parameter.
/// Unknown models return false — bridges only strip when confident.
pub fn rejects_temperature(model: &str) -> bool {
    snapshot_limits(model).is_some_and(|limits| !limits.temperature)
}

/// gpt-5.1+ 400s `reasoning_effort: "minimal"` (`none` replaced it) but stale
/// catalogs still advertise it. Matches folded/vendor-prefixed spellings and
/// the fused aggregator form (`gpt-52` = 5.2); unknown ids return false.
pub fn gpt_rejects_effort_minimal(model: &str) -> bool {
    let folded = fold(model);
    folded.match_indices("gpt-").any(|(i, _)| {
        let rest = &folded[i + 4..];
        let seg = rest.split('-').next().unwrap_or_default();
        let digits: &str = &seg[..seg.chars().take_while(char::is_ascii_digit).count()];
        let (major, minor) = match digits.len() {
            0 => return false,
            2 => (digits[..1].parse::<u32>(), digits[1..].parse::<u32>()),
            _ => {
                let minor = (seg == digits)
                    .then(|| rest.split('-').nth(1))
                    .flatten()
                    .filter(|s| !s.is_empty() && s.chars().all(|c| c.is_ascii_digit()))
                    .and_then(|s| s.parse::<u32>().ok())
                    .unwrap_or(0);
                (digits.parse::<u32>(), Ok(minor))
            }
        };
        match (major, minor) {
            (Ok(major), Ok(minor)) => major > 5 || (major == 5 && minor >= 1),
            _ => false,
        }
    })
}

/// Capability sets for this process's local llama-server. Static because
/// `ResolvedLimits.caps` borrows `'static`; context comes from `SpawnInfo`.
static HF_LOCAL_CAPS_TEXT: LazyLock<ModelLimits> = LazyLock::new(|| hf_local_caps(false));
static HF_LOCAL_CAPS_VISION: LazyLock<ModelLimits> = LazyLock::new(|| hf_local_caps(true));

fn hf_local_caps(image_input: bool) -> ModelLimits {
    ModelLimits {
        context: None,
        output: None,
        tool_call: true,
        reasoning: false,
        attachment: false,
        image_input,
        image_output: false,
        temperature: true,
        deprecated: false,
        reasoning_efforts: Vec::new(),
        pricing: None,
    }
}

/// When `model` targets this process's local llama-server, advertise the
/// server's actual spawn parameters (context it was started with, whether
/// an mmproj is loaded) instead of snapshot guesses. One aivo process runs
/// at most one local server, so any hf-style ref maps to it.
fn hf_local_limits(base_url: Option<&str>, model: &str) -> Option<ResolvedLimits> {
    crate::services::huggingface::spawn_info()
        .and_then(|info| hf_local_limits_for(info, base_url, model))
}

fn hf_local_limits_for(
    info: &crate::services::huggingface::SpawnInfo,
    base_url: Option<&str>,
    model: &str,
) -> Option<ResolvedLimits> {
    let url_hit = base_url.is_some_and(|u| u.contains(&format!("127.0.0.1:{}", info.port)));
    let model_hit =
        model == info.model_name || crate::services::huggingface::is_hf_or_local_gguf(model);
    if !url_hit && !model_hit {
        return None;
    }
    let caps: &'static ModelLimits = if info.image_input {
        &HF_LOCAL_CAPS_VISION
    } else {
        &HF_LOCAL_CAPS_TEXT
    };
    Some(ResolvedLimits {
        context: Some(info.context),
        output: None,
        caps: Some(caps),
        reasoning_efforts: Vec::new(),
    })
}

/// THE canonical limits cascade. Every consumer (claude `[1m]` auto-tag,
/// codex catalog, loopback `/v1/models`) goes through here.
pub async fn resolve_limits(
    cache: &ModelsCache,
    base_url: Option<&str>,
    model: &str,
) -> ResolvedLimits {
    let stripped = strip_context_suffix(model);
    if let Some(local) = hf_local_limits(base_url, stripped) {
        return local;
    }
    let live = match base_url {
        Some(url) => match cache.get_metadata(&full_catalog_key(url), stripped).await {
            Some(meta) => Some(meta),
            None => cache.get_metadata(url, stripped).await,
        },
        None => None,
    };
    let snap = snapshot_limits(stripped);
    // Live catalog wins when it advertises levels; else the snapshot's.
    let mut reasoning_efforts = live
        .as_ref()
        .map(|m| m.reasoning_efforts.clone())
        .filter(|v| !v.is_empty())
        .or_else(|| snap.map(|s| s.reasoning_efforts.clone()))
        .unwrap_or_default();
    if gpt_rejects_effort_minimal(stripped) {
        reasoning_efforts.retain(|e| e != "minimal");
    }
    ResolvedLimits {
        // `--max-context` override: fills an unknown window, never overrides a known one.
        context: live
            .as_ref()
            .and_then(|m| m.context_window)
            .or_else(|| snap.and_then(|s| s.context))
            .or_else(context_window_override),
        output: live
            .as_ref()
            .and_then(|m| m.max_output_tokens)
            .or_else(|| snap.and_then(|s| s.output)),
        reasoning_efforts,
        caps: snap,
    }
}

/// Process-wide `--max-context` override (tokens), 0 = unset; read as the last
/// resort in [`resolve_limits`] so every coding agent picks up a manual window.
/// An atomic, not an env var, so setting it can't race the serve threads.
static CONTEXT_WINDOW_OVERRIDE: AtomicU64 = AtomicU64::new(0);

/// Set (or clear, with 0) the manual context-window override.
pub fn set_context_window_override(tokens: u64) {
    CONTEXT_WINDOW_OVERRIDE.store(tokens, Ordering::Relaxed);
}

fn context_window_override() -> Option<u64> {
    match CONTEXT_WINDOW_OVERRIDE.load(Ordering::Relaxed) {
        0 => None,
        n => Some(n),
    }
}

/// Parse a `--max-context` size into tokens: a bare integer or a `k`/`m` suffix
/// (`200k`, `1m`, `128000`), case-insensitive. `None` if unparseable or <= 0.
pub fn parse_context_size(s: &str) -> Option<u64> {
    let lower = s.trim().to_ascii_lowercase();
    if lower.is_empty() {
        return None;
    }
    let (num, mult) = if let Some(n) = lower.strip_suffix('k') {
        (n, 1_000f64)
    } else if let Some(n) = lower.strip_suffix('m') {
        (n, 1_000_000f64)
    } else {
        (lower.as_str(), 1f64)
    };
    let num: f64 = num.trim().parse().ok()?;
    if !num.is_finite() || num <= 0.0 {
        return None;
    }
    let tokens = (num * mult).round();
    (tokens >= 1.0).then_some(tokens as u64)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(ctx: Option<u64>, out: Option<u64>, flags: String) -> LimitRow {
        vec![
            serde_json::json!(ctx),
            serde_json::json!(out),
            serde_json::json!(flags),
            serde_json::json!(""),
        ]
    }
    use crate::services::models_cache::ModelMetadata;
    use tempfile::TempDir;

    #[test]
    fn snapshot_parses_and_is_nontrivial() {
        // Catches a truncated or mangled regeneration of the embedded file.
        assert!(SNAPSHOT.len() >= 1000, "only {} entries", SNAPSHOT.len());
    }

    #[test]
    fn claude_sonnet_4_6_resolves_to_1m() {
        let hit = snapshot_limits("claude-sonnet-4-6").unwrap();
        assert_eq!(hit.context, Some(1_000_000));
        assert_eq!(hit.output, Some(64_000));
        assert!(hit.tool_call && hit.reasoning && hit.image_input);
    }

    #[test]
    fn claude_opus_4_7_resolves_to_1m() {
        assert_eq!(
            snapshot_limits("claude-opus-4-7").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn provider_prefixed_model_still_matches() {
        for id in [
            "anthropic/claude-opus-4-7",
            "us.anthropic.claude-sonnet-4-6",
            "openrouter/anthropic/claude-sonnet-4.6",
        ] {
            assert_eq!(
                snapshot_limits(id).unwrap().context,
                Some(1_000_000),
                "{id}"
            );
        }
    }

    #[test]
    fn dot_and_dash_version_spellings_match() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4.6").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn date_suffixed_id_matches_base() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4-5-20250929")
                .unwrap()
                .context,
            Some(1_000_000)
        );
    }

    #[test]
    fn context_suffix_is_stripped() {
        assert_eq!(
            snapshot_limits("claude-sonnet-4-6[1m]").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn case_insensitive_match() {
        assert_eq!(
            snapshot_limits("Claude-Sonnet-4-6").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn grok_4_3_resolves_to_1m() {
        assert_eq!(
            snapshot_limits("grok-4.3").unwrap().context,
            Some(1_000_000)
        );
        assert_eq!(
            snapshot_limits("xai/grok-4.3").unwrap().context,
            Some(1_000_000)
        );
    }

    #[test]
    fn grok_4_fast_resolves_to_2m() {
        for id in ["grok-4-fast", "x-ai/grok-4-fast", "grok-4-fast-reasoning"] {
            assert_eq!(
                snapshot_limits(id).unwrap().context,
                Some(2_000_000),
                "{id}"
            );
        }
    }

    #[test]
    fn gpt_4_1_family_resolves_to_1m_class() {
        assert_eq!(snapshot_limits("gpt-4.1").unwrap().context, Some(1_047_576));
        assert_eq!(
            snapshot_limits("openai/gpt-4.1-mini").unwrap().context,
            Some(1_047_576)
        );
    }

    #[test]
    fn short_context_models_resolve_below_1m() {
        // The old static table returned None for these; the snapshot knows
        // their real (sub-1M) limits.
        assert_eq!(
            snapshot_limits("gpt-3.5-turbo").unwrap().context,
            Some(16_385)
        );
        assert_eq!(
            snapshot_limits("claude-3-haiku").unwrap().context,
            Some(200_000)
        );
    }

    #[test]
    fn variant_only_listings_resolve_for_plain_id() {
        // poolside/laguna-m.1 is mostly listed as `…:free`; the generator
        // merges variants into the base id (262,144 = poolside's own figure).
        assert_eq!(
            snapshot_limits("poolside/laguna-m.1").unwrap().context,
            Some(262_144)
        );
        // Explicit `:free` needles resolve too (colon-strip step).
        assert_eq!(
            snapshot_limits("openrouter/poolside/laguna-m.1:free")
                .unwrap()
                .context,
            Some(262_144)
        );
    }

    #[test]
    fn image_output_flag_parses_and_queries() {
        let limits = parse_row(&row(Some(32768), Some(32768), "aig".into())).unwrap();
        assert!(limits.image_input);
        assert!(limits.image_output);
        assert!(
            !parse_row(&row(None, None, "tai".into()))
                .unwrap()
                .image_output
        );
        // The synced snapshot knows at least one image-output model.
        assert!(model_generates_images("gemini-2.5-flash-image"));
        assert!(!model_generates_images("deepseek-chat"));
        assert!(!model_generates_images("totally-unknown-model-xyz"));
    }

    #[test]
    fn temperature_and_deprecated_flags_parse() {
        // o-series and forced-reasoning claude variants reject temperature.
        assert!(rejects_temperature("o3"));
        assert!(rejects_temperature("openai/gpt-5.4"));
        assert!(rejects_temperature("claude-opus-4-7"));
        // Normal models keep it; unknown models are never stripped.
        assert!(!rejects_temperature("claude-sonnet-4-6"));
        assert!(!rejects_temperature("deepseek-chat"));
        assert!(!rejects_temperature("totally-unknown-model-xyz"));
        // Some model in the snapshot carries the deprecated flag.
        assert!(SNAPSHOT.values().any(|l| l.deprecated));
    }

    #[test]
    fn fixed_temperature_survives_fold_collisions() {
        // `gpt-5.4` and `gpt-5-4` fold to one key with equal context, so the
        // tie-break alone would let whichever sorts first decide sampling
        // support. Upstream disagrees per spelling; the restrictive side wins.
        for id in [
            "gpt-5.1",
            "gpt-5.2",
            "gpt-5.3-codex",
            "gpt-5.4",
            "gpt-5.4-nano",
            "anthropic.claude-opus-4-8",
        ] {
            assert!(rejects_temperature(id), "{id} must reject sampling params");
        }
    }

    #[test]
    fn reasoning_efforts_parse() {
        let efforts = &snapshot_limits("o3").unwrap().reasoning_efforts;
        assert!(efforts.iter().any(|e| e == "medium"), "{efforts:?}");
        assert!(
            snapshot_limits("deepseek-chat")
                .unwrap()
                .reasoning_efforts
                .is_empty()
        );
    }

    #[test]
    fn unknown_models_return_none() {
        assert_eq!(snapshot_limits("totally-unknown-model-xyz"), None);
        assert_eq!(snapshot_limits(""), None);
    }

    #[test]
    fn parse_context_size_accepts_suffixes_and_rejects_garbage() {
        assert_eq!(parse_context_size("128000"), Some(128_000));
        assert_eq!(parse_context_size("200k"), Some(200_000));
        assert_eq!(parse_context_size("200K"), Some(200_000));
        assert_eq!(parse_context_size("1m"), Some(1_000_000));
        assert_eq!(parse_context_size("2M"), Some(2_000_000));
        assert_eq!(parse_context_size("1.5m"), Some(1_500_000));
        assert_eq!(parse_context_size("  256k "), Some(256_000));
        // Rejected: empty, non-numeric, zero/negative, bad suffix.
        for bad in ["", "abc", "0", "-5", "10g", "k"] {
            assert_eq!(parse_context_size(bad), None, "{bad:?}");
        }
    }

    #[test]
    fn gpt_rejects_effort_minimal_covers_5_1_plus_spellings() {
        for id in [
            "gpt-5.1",
            "gpt-5-1-codex-max",
            "gpt-5.2",
            "gpt-5-2",
            "gpt-5.3-codex",
            "gpt-5.4-mini-2026-03-17",
            "gpt-5.6-luna",
            "openai/gpt-5.4",
            "openai.gpt-5.5",
            "databricks-gpt-5-2",
            "openai-gpt-52", // fused aggregator spelling
            "gpt-6",
        ] {
            assert!(gpt_rejects_effort_minimal(id), "{id} must reject minimal");
        }
        for id in [
            "gpt-5",
            "gpt-5-chat",
            "gpt-5-mini",
            "gpt-4.1",
            "gpt-41", // fused 4.1
            "chatgpt-4o-latest",
            "gpt-oss-120b",
            "o3",
            "claude-opus-4-8",
        ] {
            assert!(!gpt_rejects_effort_minimal(id), "{id} must keep minimal");
        }
    }

    #[test]
    fn snapshot_strips_minimal_for_gpt_5_1_plus() {
        // The load-time retain protects stale overlay caches; "none" must
        // survive it — 5.1+ accept none (it replaced minimal).
        use std::collections::BTreeMap;
        let stale_row = |efforts: &str| {
            vec![
                serde_json::json!(400_000),
                serde_json::json!(128_000),
                serde_json::json!("tr"),
                serde_json::json!(efforts),
            ]
        };
        let mut rows: BTreeMap<String, LimitRow> = BTreeMap::new();
        rows.insert("gpt-5.2".into(), stale_row("none,minimal,low,medium,high"));
        rows.insert("gpt-5".into(), stale_row("minimal,low,medium,high"));
        let folded = fold_rows(rows);
        assert_eq!(
            folded["gpt-5-2"].reasoning_efforts,
            ["none", "low", "medium", "high"].map(String::from)
        );
        assert_eq!(
            folded["gpt-5"].reasoning_efforts,
            ["minimal", "low", "medium", "high"].map(String::from)
        );

        // And the shipped snapshot agrees end-to-end.
        let g52 = &snapshot_limits("gpt-5.2").unwrap().reasoning_efforts;
        assert!(g52.iter().any(|e| e == "none"), "{g52:?}");
        assert!(!g52.iter().any(|e| e == "minimal"), "{g52:?}");
        let g5 = &snapshot_limits("gpt-5").unwrap().reasoning_efforts;
        assert!(g5.iter().any(|e| e == "minimal"), "{g5:?}");
    }

    #[test]
    fn pricing_parses_and_survives_fold_collisions() {
        use std::collections::BTreeMap;
        let mut rows: BTreeMap<String, LimitRow> = BTreeMap::new();
        // Dash spelling (sorts first, same context) has no pricing; the dot
        // spelling carries the vendor's. The folded row must keep the prices.
        rows.insert(
            "bar-2-0".into(),
            row(Some(100_000), Some(8_000), "t".into()),
        );
        rows.insert(
            "bar-2.0".into(),
            vec![
                serde_json::json!(100_000),
                serde_json::json!(8_000),
                serde_json::json!("t"),
                serde_json::json!(""),
                serde_json::json!(5.0),
                serde_json::json!(25.0),
                serde_json::json!(0.5),
                serde_json::json!(6.25),
            ],
        );
        let folded = fold_rows(rows);
        let pricing = folded["bar-2-0"]
            .pricing
            .expect("pricing merged across fold");
        assert_eq!(pricing.input, Some(5.0));
        assert_eq!(pricing.cache_write, Some(6.25));

        let tokens = crate::services::session_store::SessionTokens {
            prompt_tokens: 1_000_000,
            completion_tokens: 100_000,
            cache_read_tokens: 500_000,
            cache_write_tokens: 200_000,
        };
        // 300k fresh × $5 + 500k read × $0.5 + 200k write × $6.25 + 100k out × $25
        let cost = pricing.cost_usd(&tokens).unwrap();
        assert!((cost - 5.5).abs() < 1e-9, "got {cost}");
        // No input/output price → no estimate.
        assert!(Pricing::default().cost_usd(&tokens).is_none());
    }

    #[test]
    fn embedded_snapshot_carries_vendor_pricing() {
        let p = model_pricing("claude-opus-4-8").expect("opus is priced");
        assert_eq!(p.input, Some(5.0));
        assert_eq!(p.output, Some(25.0));
        assert!(model_pricing("definitely-not-a-model").is_none());
    }

    #[test]
    fn override_rows_win_over_embedded_floor() {
        use std::collections::BTreeMap;
        let mut base: BTreeMap<String, LimitRow> = BTreeMap::new();
        base.insert("model-a".into(), row(Some(100), Some(10), "t".into()));
        base.insert("model-b".into(), row(Some(200), None, String::new()));
        let mut over: BTreeMap<String, LimitRow> = BTreeMap::new();
        // model-a refreshed to a *smaller* context — fresh data still wins.
        over.insert("model-a".into(), row(Some(50), Some(5), "tr".into()));
        over.insert("model-c".into(), row(Some(300), None, String::new()));
        let folded = overlay_override(base, over);
        assert_eq!(folded["model-a"].context, Some(50));
        assert!(folded["model-a"].reasoning);
        assert_eq!(folded["model-b"].context, Some(200)); // untouched embedded id
        assert_eq!(folded["model-c"].context, Some(300)); // new id from override
    }

    #[test]
    fn stale_override_without_g_flag_keeps_embedded_image_output() {
        use std::collections::BTreeMap;
        // Regression: an override cache written by a pre-`g` binary (flags
        // "rai") shadowed the embedded snapshot's "raig" and hid every image
        // model from the generator picker until a manual resync.
        let mut base: BTreeMap<String, LimitRow> = BTreeMap::new();
        base.insert(
            "gemini-2.5-flash-image".into(),
            row(Some(32_768), Some(32_768), "aig".into()),
        );
        let mut over: BTreeMap<String, LimitRow> = BTreeMap::new();
        over.insert(
            "gemini-2.5-flash-image".into(),
            row(Some(32_768), Some(32_768), "rai".into()),
        );
        let folded = overlay_override(base, over);
        let m = &folded["gemini-2-5-flash-image"];
        assert!(m.image_output, "embedded capability survives a stale cache");
        assert!(m.reasoning, "fresh override fields still win");
    }

    #[test]
    fn override_wins_across_dot_dash_spelling_with_smaller_context() {
        use std::collections::BTreeMap;
        // The embedded floor lists the model dot-spelled with a *larger* context;
        // the fresh override lists it dash-spelled with a smaller one. Both fold
        // to the same id — the override must still win. Regression for the
        // merge-raw-then-fold path, where `fold_rows`' larger-context tiebreak
        // kept the stale embedded value and silently dropped the refresh.
        let mut base: BTreeMap<String, LimitRow> = BTreeMap::new();
        base.insert(
            "claude-sonnet-4.6".into(),
            row(Some(1_000_000), Some(64_000), "t".into()),
        );
        let mut over: BTreeMap<String, LimitRow> = BTreeMap::new();
        over.insert(
            "claude-sonnet-4-6".into(),
            row(Some(800_000), Some(32_000), "tr".into()),
        );
        let folded = overlay_override(base, over);
        assert_eq!(folded.len(), 1, "dot and dash fold to one id");
        assert_eq!(folded["claude-sonnet-4-6"].context, Some(800_000));
        assert_eq!(folded["claude-sonnet-4-6"].output, Some(32_000));
        assert!(folded["claude-sonnet-4-6"].reasoning);
    }

    #[test]
    fn fold_collapses_dot_and_dash_keeping_larger_context() {
        use std::collections::BTreeMap;
        let mut rows: BTreeMap<String, LimitRow> = BTreeMap::new();
        rows.insert("foo-1.5".into(), row(Some(128_000), None, "t".into()));
        rows.insert("foo-1-5".into(), row(Some(200_000), None, "t".into()));
        let folded = fold_rows(rows);
        // Both fold to `foo-1-5`; the larger context wins regardless of order.
        assert_eq!(folded.len(), 1);
        assert_eq!(folded["foo-1-5"].context, Some(200_000));
    }

    #[test]
    fn override_path_sits_in_cache_dir() {
        if let Some(p) = override_model_limits_path() {
            assert_eq!(p.file_name().unwrap(), "model_limits.json");
            assert_eq!(
                p.parent().unwrap().file_name().unwrap(),
                crate::services::paths::CACHE_DIR
            );
        }
    }

    #[tokio::test]
    async fn cascade_prefers_live_cache_over_snapshot() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let mut metadata = std::collections::HashMap::new();
        metadata.insert(
            "claude-sonnet-4-6".to_string(),
            ModelMetadata {
                context_window: Some(200_000),
                ..Default::default()
            },
        );
        cache
            .set_with_metadata(
                &full_catalog_key("https://api.example.com"),
                vec!["claude-sonnet-4-6".to_string()],
                metadata,
            )
            .await;
        let resolved =
            resolve_limits(&cache, Some("https://api.example.com"), "claude-sonnet-4-6").await;
        assert_eq!(resolved.context, Some(200_000));
        // Cache has no output → snapshot fills the gap (per-field merge).
        assert_eq!(resolved.output, Some(64_000));
        assert!(resolved.caps.unwrap().tool_call);
    }

    #[tokio::test]
    async fn reasoning_efforts_come_from_live_catalog_for_unknown_model() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let mut metadata = std::collections::HashMap::new();
        metadata.insert(
            "aivo/starter".to_string(),
            ModelMetadata {
                context_window: Some(1_000_000),
                reasoning_efforts: vec!["low".into(), "medium".into(), "high".into()],
                ..Default::default()
            },
        );
        cache
            .set_with_metadata(
                &full_catalog_key("https://api.getaivo.dev"),
                vec!["aivo/starter".to_string()],
                metadata,
            )
            .await;
        // The snapshot has no `aivo/starter`; the levels come from the catalog.
        let resolved =
            resolve_limits(&cache, Some("https://api.getaivo.dev"), "aivo/starter").await;
        assert_eq!(resolved.reasoning_efforts, vec!["low", "medium", "high"]);
    }

    #[tokio::test]
    async fn cascade_falls_back_to_snapshot_on_cold_cache() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let resolved =
            resolve_limits(&cache, Some("https://api.example.com"), "claude-sonnet-4-6").await;
        assert_eq!(resolved.context, Some(1_000_000));
        assert_eq!(resolved.output, Some(64_000));
    }

    #[test]
    fn hf_local_override_matches_loopback_url_name_and_refs() {
        let info = crate::services::huggingface::SpawnInfo {
            port: 18080,
            context: 40_960,
            image_input: true,
            model_name: "Qwen2.5-0.5B-Instruct-GGUF".to_string(),
        };
        // Loopback base URL.
        let by_url = hf_local_limits_for(&info, Some("http://127.0.0.1:18080/v1"), "anything")
            .expect("url match");
        assert_eq!(by_url.context, Some(40_960));
        assert!(by_url.caps.unwrap().image_input);
        assert!(by_url.caps.unwrap().tool_call);
        // Display model name.
        assert!(hf_local_limits_for(&info, None, "Qwen2.5-0.5B-Instruct-GGUF").is_some());
        // hf-style refs map to the (only) local server.
        assert!(hf_local_limits_for(&info, None, "hf:Qwen/Qwen2.5-0.5B-Instruct-GGUF").is_some());
        // Unrelated remote model on an unrelated URL: untouched.
        assert!(
            hf_local_limits_for(&info, Some("https://api.example.com"), "claude-sonnet-4-6")
                .is_none()
        );
    }

    #[test]
    fn hf_local_override_text_only_without_mmproj() {
        let info = crate::services::huggingface::SpawnInfo {
            port: 18081,
            context: 32_768,
            image_input: false,
            model_name: "m".to_string(),
        };
        let limits = hf_local_limits_for(&info, Some("http://127.0.0.1:18081/v1"), "m").unwrap();
        assert!(!limits.caps.unwrap().image_input);
        assert_eq!(limits.output, None);
    }

    #[tokio::test]
    async fn cascade_unknown_everywhere_is_empty() {
        let dir = TempDir::new().unwrap();
        let cache = ModelsCache::with_path(dir.path().join("models-cache.json"));
        let resolved = resolve_limits(&cache, None, "totally-unknown-model-xyz").await;
        assert_eq!(resolved.context, None);
        assert_eq!(resolved.output, None);
        assert!(resolved.caps.is_none());
    }
}
