use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};

use crate::services::effort::{extract_openai_effort, gemini_thinking_config};
use crate::services::http_utils::current_unix_ts;
use crate::services::model_names::google_native_model_name;

/// Documented Gemini placeholder for the `thoughtSignature` field on
/// functionCall parts whose original signature is unavailable (e.g. histories
/// not generated by Gemini, or any case where aivo's per-process cache misses).
/// Source: https://ai.google.dev/gemini-api/docs/thought-signatures
pub(crate) const SKIP_THOUGHT_SIGNATURE_PLACEHOLDER: &str = "skip_thought_signature_validator";

/// How long a captured signature stays usable. Gemini's strict validation
/// only covers the *current* assistant turn, so signatures older than this
/// have very low odds of being needed and are pruned to bound disk growth.
const SIGNATURE_TTL_SECS: u64 = 24 * 60 * 60;

#[derive(Clone, Serialize, Deserialize)]
struct SignatureEntry {
    signature: String,
    captured_at: u64,
}

fn cache_key(model: &str, call_id: &str) -> String {
    // Keying by (model, call_id) prevents cross-model contamination — a stale
    // signature captured against `gemini-2.5-pro` would otherwise be replayed
    // against `gemini-3.1-pro-preview` and trigger a 400.
    format!("{}|{}", model, call_id)
}

/// Process-wide cache of `(model, call_id) -> thoughtSignature`. Gemini-3
/// returns a `thoughtSignature` on functionCall response parts and rejects
/// subsequent turns whose history doesn't echo it back. Claude Code (the
/// upstream) drops unknown fields on tool blocks, so we maintain the mapping
/// here and re-attach signatures when the request flows back through.
///
/// Persisted to disk so that a process restart between turns
/// (e.g., re-launching `aivo run gemini`) doesn't lose the signatures.
fn signature_cache() -> &'static Mutex<HashMap<String, SignatureEntry>> {
    static CACHE: OnceLock<Mutex<HashMap<String, SignatureEntry>>> = OnceLock::new();
    CACHE.get_or_init(|| {
        let mut map = HashMap::new();
        if let Some(disk) = read_signature_store_from_disk() {
            map.extend(disk);
        }
        prune_expired(&mut map, current_unix_ts());
        Mutex::new(map)
    })
}

fn signature_store_path() -> Option<PathBuf> {
    crate::services::system_env::home_dir().map(|p| {
        p.join(".config")
            .join("aivo")
            .join("gemini_thought_signatures.json")
    })
}

fn read_signature_store_from_disk() -> Option<HashMap<String, SignatureEntry>> {
    let path = signature_store_path()?;
    let contents = std::fs::read_to_string(&path).ok()?;
    serde_json::from_str::<HashMap<String, SignatureEntry>>(&contents).ok()
}

fn prune_expired(map: &mut HashMap<String, SignatureEntry>, now: u64) {
    map.retain(|_, entry| now.saturating_sub(entry.captured_at) < SIGNATURE_TTL_SECS);
}

/// Best-effort write of the cache to disk. Reads the current disk state and
/// merges the in-memory cache on top before writing back, so concurrent
/// `aivo` processes preserve each other's recently-captured entries instead
/// of last-writer-wins clobbering them. Errors are swallowed: a missing
/// signature degrades to `SKIP_THOUGHT_SIGNATURE_PLACEHOLDER` rather than
/// failing the request outright.
fn persist_signature_store(map: &HashMap<String, SignatureEntry>) {
    let Some(path) = signature_store_path() else {
        return;
    };
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let mut merged = read_signature_store_from_disk().unwrap_or_default();
    // Newer in-memory entries override older on-disk entries for the same key.
    for (key, entry) in map {
        let keep_existing = merged
            .get(key)
            .map(|existing| existing.captured_at > entry.captured_at)
            .unwrap_or(false);
        if !keep_existing {
            merged.insert(key.clone(), entry.clone());
        }
    }
    prune_expired(&mut merged, current_unix_ts());
    let Ok(json) = serde_json::to_string(&merged) else {
        return;
    };
    write_string_atomic(&path, &json);
}

/// Synchronous atomic write: temp file under the same dir + rename + 0o600
/// on Unix. Mirrors `atomic_write::atomic_write_secure` which is async.
fn write_string_atomic(path: &PathBuf, contents: &str) {
    use std::io::Write;
    let Some(parent) = path.parent() else {
        return;
    };
    let temp_path = parent.join(format!(
        ".gemini_thought_signatures.{}.tmp",
        current_unix_ts()
    ));
    let Ok(mut file) = std::fs::File::create(&temp_path) else {
        return;
    };
    if file.write_all(contents.as_bytes()).is_err() {
        let _ = std::fs::remove_file(&temp_path);
        return;
    }
    let _ = file.sync_all();
    drop(file);
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(&temp_path, std::fs::Permissions::from_mode(0o600));
    }
    let _ = std::fs::rename(&temp_path, path);
}

fn remember_signature(model: &str, call_id: &str, signature: &str) {
    if model.is_empty() || call_id.is_empty() || signature.is_empty() {
        return;
    }
    let key = cache_key(model, call_id);
    let entry = SignatureEntry {
        signature: signature.to_string(),
        captured_at: current_unix_ts(),
    };
    let snapshot = if let Ok(mut cache) = signature_cache().lock() {
        cache.insert(key, entry);
        Some(cache.clone())
    } else {
        None
    };
    if let Some(snapshot) = snapshot {
        persist_signature_store(&snapshot);
    }
}

fn lookup_signature(model: &str, call_id: &str) -> Option<String> {
    if model.is_empty() || call_id.is_empty() {
        return None;
    }
    let key = cache_key(model, call_id);
    let now = current_unix_ts();
    let cache = signature_cache().lock().ok()?;
    cache
        .get(&key)
        .filter(|entry| now.saturating_sub(entry.captured_at) < SIGNATURE_TTL_SECS)
        .map(|entry| entry.signature.clone())
}

/// Gemini's `functionDeclarations` only accepts a subset of JSON Schema fields.
/// Recursively strip unsupported fields like `$schema`, `additionalProperties`,
/// `propertyNames`, etc. that OpenAI-compatible tool definitions commonly include.
pub fn sanitize_schema_for_gemini(schema: &Value) -> Value {
    let Some(obj) = schema.as_object() else {
        return schema.clone();
    };

    // Gemini rejects schemas where `anyOf` appears alongside sibling
    // schema-defining fields (`type`, `properties`, `required`, etc.) with
    // 400 INVALID_ARGUMENT: "When using any_of, it must be the only field set."
    // Emit only `anyOf` (recursively sanitized) at this level when present.
    if let Some(any_of) = obj.get("anyOf").and_then(|v| v.as_array()) {
        let cleaned_variants: Vec<Value> = any_of.iter().map(sanitize_schema_for_gemini).collect();
        let mut out = serde_json::Map::new();
        out.insert("anyOf".to_string(), Value::Array(cleaned_variants));
        return Value::Object(out);
    }

    static ALLOWED: &[&str] = &[
        "type",
        "description",
        "properties",
        "required",
        "items",
        "enum",
        "format",
        "nullable",
        "minimum",
        "maximum",
        "minItems",
        "maxItems",
    ];

    let mut cleaned = serde_json::Map::new();
    for key in ALLOWED {
        if let Some(value) = obj.get(*key) {
            let sanitized = match *key {
                "properties" => {
                    if let Some(props) = value.as_object() {
                        let mut new_props = serde_json::Map::new();
                        for (k, v) in props {
                            new_props.insert(k.clone(), sanitize_schema_for_gemini(v));
                        }
                        Value::Object(new_props)
                    } else {
                        value.clone()
                    }
                }
                "items" => sanitize_schema_for_gemini(value),
                _ => value.clone(),
            };
            cleaned.insert(key.to_string(), sanitized);
        }
    }

    // Ensure type and properties exist for object schemas
    // Treat null type the same as missing
    if !cleaned.contains_key("type") || cleaned.get("type").is_some_and(|v| v.is_null()) {
        cleaned.insert("type".to_string(), json!("object"));
    }
    if cleaned.get("type").and_then(|v| v.as_str()) == Some("object")
        && !cleaned.contains_key("properties")
    {
        cleaned.insert("properties".to_string(), json!({}));
    }

    Value::Object(cleaned)
}

#[derive(Clone, Copy, Debug)]
pub struct OpenAIToGeminiConfig {
    pub default_model: &'static str,
}

pub fn openai_chat_model(body: &Value, default_model: &str) -> String {
    body.get("model")
        .and_then(|m| m.as_str())
        .unwrap_or(default_model)
        .to_string()
}

pub fn build_google_generate_content_url(base_url: &str, model: &str) -> String {
    build_google_content_url(base_url, model, false)
}

pub fn build_google_stream_generate_content_url(base_url: &str, model: &str) -> String {
    build_google_content_url(base_url, model, true)
}

fn build_google_content_url(base_url: &str, model: &str, stream: bool) -> String {
    let base = base_url.trim_end_matches('/');
    let model = google_native_model_name(model);
    let suffix = if stream {
        ":streamGenerateContent?alt=sse"
    } else {
        ":generateContent"
    };
    if base.ends_with("/models") {
        format!("{}/{}{}", base, model, suffix)
    } else if base.ends_with("/v1beta") || base.ends_with("/v1") {
        format!("{}/models/{}{}", base, model, suffix)
    } else {
        format!("{}/v1beta/models/{}{}", base, model, suffix)
    }
}

pub fn convert_openai_chat_to_gemini_request(body: &Value, config: &OpenAIToGeminiConfig) -> Value {
    let mut system_parts: Vec<String> = Vec::new();
    let mut contents: Vec<Value> = Vec::new();
    let mut tool_names_by_call_id: HashMap<String, String> = HashMap::new();
    let request_model = openai_chat_model(body, config.default_model);

    if let Some(messages) = body.get("messages").and_then(|m| m.as_array()) {
        let mut iter = messages.iter().peekable();
        while let Some(message) = iter.next() {
            let role = message
                .get("role")
                .and_then(|r| r.as_str())
                .unwrap_or("user");

            match role {
                "system" => {
                    let text = extract_openai_text(message.get("content"));
                    if !text.is_empty() {
                        system_parts.push(text);
                    }
                }
                "assistant" => {
                    let mut parts: Vec<Value> = Vec::new();
                    let text = extract_openai_text(message.get("content"));
                    if !text.is_empty() {
                        parts.push(json!({ "text": text }));
                    }
                    if let Some(tool_calls) = message.get("tool_calls").and_then(|v| v.as_array()) {
                        for (tc_index, tool_call) in tool_calls.iter().enumerate() {
                            let name = tool_call
                                .get("function")
                                .and_then(|f| f.get("name"))
                                .and_then(|v| v.as_str())
                                .unwrap_or("");
                            let call_id = tool_call
                                .get("id")
                                .and_then(|v| v.as_str())
                                .filter(|id| !id.is_empty())
                                .map(ToOwned::to_owned)
                                .unwrap_or_else(|| format!("call_{tc_index}"));
                            tool_names_by_call_id.insert(call_id.clone(), name.to_string());
                            let args = tool_call
                                .get("function")
                                .and_then(|f| f.get("arguments"))
                                .and_then(|v| v.as_str())
                                .and_then(|s| serde_json::from_str::<Value>(s).ok())
                                .unwrap_or_else(|| json!({}));
                            let mut part = json!({
                                "functionCall": {
                                    "id": call_id,
                                    "name": name,
                                    "args": args
                                }
                            });
                            // Gemini-3's signature is per-turn, attached to the
                            // first part only. Real signature from this
                            // process's history if cached; otherwise the
                            // documented Google placeholder so we don't 400 on
                            // missing thought_signature. See:
                            // https://ai.google.dev/gemini-api/docs/thought-signatures
                            if tc_index == 0 {
                                let sig = lookup_signature(&request_model, &call_id)
                                    .unwrap_or_else(|| {
                                        SKIP_THOUGHT_SIGNATURE_PLACEHOLDER.to_string()
                                    });
                                part["thoughtSignature"] = Value::String(sig);
                            }
                            parts.push(part);
                        }
                    }
                    if !parts.is_empty() {
                        contents.push(json!({ "role": "model", "parts": parts }));
                    }
                }
                "tool" => {
                    // Gemini validates parallel tool responses as one logical
                    // user step. Group consecutive OpenAI `role: tool` messages
                    // so assistant[FC1,FC2], tool(FR1), tool(FR2) becomes
                    // model[FC1,FC2], user[FR1,FR2].
                    let mut parts = vec![build_tool_response_part(message, &tool_names_by_call_id)];
                    while iter
                        .peek()
                        .and_then(|m| m.get("role"))
                        .and_then(|r| r.as_str())
                        == Some("tool")
                    {
                        let next = iter.next().expect("peeked tool message");
                        parts.push(build_tool_response_part(next, &tool_names_by_call_id));
                    }
                    contents.push(json!({ "role": "user", "parts": parts }));
                }
                _ => {
                    let parts = extract_openai_parts_for_gemini(message.get("content"));
                    contents.push(json!({
                        "role": "user",
                        "parts": parts,
                    }));
                }
            }
        }
    }

    let mut request = json!({
        "contents": contents,
    });

    if !system_parts.is_empty() {
        request["systemInstruction"] = json!({
            "parts": [{
                "text": system_parts.join("\n\n")
            }]
        });
    }

    if let Some(tools) = body.get("tools").and_then(|t| t.as_array()) {
        let declarations: Vec<Value> = tools
            .iter()
            .filter(|tool| tool.get("type").and_then(|v| v.as_str()) == Some("function"))
            .map(|tool| {
                json!({
                    "name": tool.get("function").and_then(|f| f.get("name")).cloned().unwrap_or_default(),
                    "description": tool.get("function").and_then(|f| f.get("description")).cloned().unwrap_or(json!("")),
                    "parameters": sanitize_schema_for_gemini(
                        tool.get("function").and_then(|f| f.get("parameters")).unwrap_or(&json!({"type": "object", "properties": {}}))
                    )
                })
            })
            .collect();
        if !declarations.is_empty() {
            request["tools"] = json!([{
                "functionDeclarations": declarations
            }]);
        }
    }

    if let Some(choice) = body.get("tool_choice") {
        let function_calling_config = match choice {
            Value::String(value) if value == "auto" => Some(json!({ "mode": "AUTO" })),
            Value::String(value) if value == "none" => Some(json!({ "mode": "NONE" })),
            Value::String(value) if value == "required" => Some(json!({ "mode": "ANY" })),
            Value::Object(obj) if obj.get("type").and_then(|v| v.as_str()) == Some("function") => {
                obj.get("function")
                    .and_then(|f| f.get("name"))
                    .and_then(|v| v.as_str())
                    .map(|name| {
                        json!({
                            "mode": "ANY",
                            "allowedFunctionNames": [name]
                        })
                    })
            }
            _ => None,
        };
        if let Some(config_value) = function_calling_config {
            request["toolConfig"] = json!({ "functionCallingConfig": config_value });
        }
    }

    let mut generation = serde_json::Map::new();
    if let Some(v) = body.get("max_tokens") {
        generation.insert("maxOutputTokens".to_string(), v.clone());
    }
    if let Some(v) = body.get("temperature") {
        generation.insert("temperature".to_string(), v.clone());
    }
    if let Some(v) = body.get("top_p") {
        generation.insert("topP".to_string(), v.clone());
    }
    if let Some(v) = body.get("top_k") {
        generation.insert("topK".to_string(), v.clone());
    }
    if let Some(v) = body.get("seed") {
        generation.insert("seed".to_string(), v.clone());
    }
    // OpenAI `response_format: {type: "json_object"}` → Gemini
    // `responseMimeType: application/json`. Other response_format shapes
    // (json_schema with strict schema) are not converted yet.
    if let Some(rf) = body.get("response_format")
        && rf.get("type").and_then(|v| v.as_str()) == Some("json_object")
    {
        generation.insert(
            "responseMimeType".to_string(),
            Value::String("application/json".to_string()),
        );
    }
    if let Some(v) = body.get("stop") {
        generation.insert("stopSequences".to_string(), v.clone());
    }
    // OpenAI `reasoning_effort` → Gemini 3 `thinkingConfig.thinking_level`.
    // Without this, callers asking for "high" reasoning silently get Gemini's
    // dynamic-thinking default. `thinking_level` is Gemini-3-only; older
    // models ignore it (current code has no Gemini-2.5 thinkingBudget path).
    if !generation.contains_key("thinkingConfig")
        && let Some(effort) = extract_openai_effort(body)
        && let Some(cfg) = gemini_thinking_config(effort)
    {
        generation.insert("thinkingConfig".to_string(), cfg);
    }
    if !generation.is_empty() {
        request["generationConfig"] = Value::Object(generation);
    }

    if request["contents"].as_array().is_none_or(|c| c.is_empty()) {
        request["contents"] = json!([{
            "role": "user",
            "parts": [{ "text": "" }]
        }]);
    }

    let _ = config.default_model;
    request
}

pub fn convert_gemini_to_openai_chat_response(resp: &Value, fallback_model: &str) -> Value {
    let candidate = resp
        .get("candidates")
        .and_then(|v| v.as_array())
        .and_then(|arr| arr.first())
        .cloned()
        .unwrap_or_else(|| json!({}));
    let parts = candidate
        .get("content")
        .and_then(|content| content.get("parts"))
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();

    let mut text_parts: Vec<String> = Vec::new();
    let mut tool_calls: Vec<Value> = Vec::new();
    // The first part-position-based signature stands in for any non-functionCall
    // part (text, inlineData) that needs to be replayed in image-edit / thinking
    // flows. Per spec, signatures attach to the first emitted part of each
    // logical step, so we anchor it to the first tool call we see by
    // synthesizing a stable "turn" call_id.
    let mut leading_part_signature: Option<String> = None;
    for (index, part) in parts.iter().enumerate() {
        if let Some(text) = part.get("text").and_then(|v| v.as_str())
            && !text.is_empty()
        {
            text_parts.push(text.to_string());
        }
        if leading_part_signature.is_none()
            && let Some(sig) = part.get("thoughtSignature").and_then(|v| v.as_str())
            && !sig.is_empty()
        {
            leading_part_signature = Some(sig.to_string());
        }
        if let Some(function_call) = part.get("functionCall") {
            let args = function_call
                .get("args")
                .cloned()
                .unwrap_or_else(|| json!({}));
            let id = function_call
                .get("id")
                .and_then(|v| v.as_str())
                .filter(|id| !id.is_empty())
                .map(ToOwned::to_owned)
                .unwrap_or_else(|| format!("call_{index}"));
            if let Some(sig) = part.get("thoughtSignature").and_then(|v| v.as_str()) {
                remember_signature(fallback_model, &id, sig);
            } else if let Some(sig) = leading_part_signature.as_deref() {
                // Tool call without its own signature but a sibling text/inlineData
                // part carried one for this step — associate it with this call_id
                // so a subsequent turn replaying the same call_id still has it.
                remember_signature(fallback_model, &id, sig);
            }
            tool_calls.push(json!({
                "id": id,
                "type": "function",
                "function": {
                    "name": function_call.get("name").cloned().unwrap_or(json!("")),
                    "arguments": serde_json::to_string(&args).unwrap_or_else(|_| "{}".to_string())
                }
            }));
        }
    }

    let raw_finish_reason = candidate
        .get("finishReason")
        .and_then(|v| v.as_str())
        .unwrap_or("STOP");
    let finish_reason = match raw_finish_reason {
        "MAX_TOKENS" => "length",
        // RECITATION = Gemini detected the output verbatim-quotes training
        // data and blocked the response. Closer to OpenAI's "content_filter"
        // than to a normal stop.
        "SAFETY" | "RECITATION" => "content_filter",
        _ if !tool_calls.is_empty() => "tool_calls",
        _ => "stop",
    };

    let mut message = json!({
        "role": "assistant",
        "content": if text_parts.is_empty() { Value::Null } else { Value::String(text_parts.join("\n")) }
    });
    if message["content"].is_null()
        && let Some(obj) = message.as_object_mut()
    {
        obj.remove("content");
    }
    if !tool_calls.is_empty() {
        message["tool_calls"] = Value::Array(tool_calls);
    }

    let prompt_tokens = resp
        .get("usageMetadata")
        .and_then(|u| u.get("promptTokenCount"))
        .and_then(|v| v.as_u64())
        .unwrap_or(0);
    let completion_tokens = resp
        .get("usageMetadata")
        .and_then(|u| u.get("candidatesTokenCount"))
        .and_then(|v| v.as_u64())
        .unwrap_or(0);
    let cache_read_input_tokens = resp
        .get("usageMetadata")
        .and_then(|u| u.get("cachedContentTokenCount"))
        .and_then(|v| v.as_u64());

    let mut usage = json!({
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": prompt_tokens + completion_tokens
    });
    if let Some(value) = cache_read_input_tokens {
        usage["cache_read_input_tokens"] = json!(value);
    }

    json!({
        "id": resp.get("responseId").cloned().unwrap_or(json!("chatcmpl-aivo")),
        "object": "chat.completion",
        "created": current_unix_ts(),
        "model": fallback_model,
        "choices": [{
            "index": 0,
            "message": message,
            "finish_reason": finish_reason
        }],
        "usage": usage
    })
}

fn parse_tool_content(content: Option<&Value>) -> Value {
    match content {
        Some(Value::String(value)) => {
            serde_json::from_str(value).unwrap_or_else(|_| json!({ "content": value }))
        }
        Some(other) => other.clone(),
        None => json!({}),
    }
}

fn build_tool_response_part(
    tool_message: &Value,
    tool_names_by_call_id: &HashMap<String, String>,
) -> Value {
    let call_id = tool_message
        .get("tool_call_id")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    // Gemini matches by function name, not ID — fall back to call_id
    // when the assistant message with the original tool_call is not in history.
    let name = tool_names_by_call_id
        .get(call_id)
        .filter(|n| !n.is_empty())
        .cloned()
        .unwrap_or_else(|| call_id.to_string());
    let response = parse_tool_content(tool_message.get("content"));
    json!({
        "functionResponse": {
            "id": call_id,
            "name": name,
            "response": response
        }
    })
}

fn extract_openai_text(content: Option<&Value>) -> String {
    match content {
        Some(Value::String(s)) => s.clone(),
        Some(Value::Array(parts)) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(|v| v.as_str()))
            .collect::<Vec<_>>()
            .join("\n"),
        Some(Value::Null) | None => String::new(),
        Some(other) => other.to_string(),
    }
}

/// Convert OpenAI Chat Completions content (string or array of content parts)
/// into a Vec of Gemini parts. Preserves `image_url` parts as `inlineData`
/// (for `data:` URIs) or `fileData` (for HTTP URLs). Empty content yields a
/// single empty-text part so the resulting Gemini turn is still well-formed.
fn extract_openai_parts_for_gemini(content: Option<&Value>) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::new();
    match content {
        Some(Value::String(s)) => {
            out.push(json!({ "text": s }));
        }
        Some(Value::Array(parts)) => {
            for part in parts {
                if let Some(p) = openai_content_part_to_gemini_part(part) {
                    out.push(p);
                }
            }
        }
        Some(Value::Null) | None => {}
        Some(other) => {
            out.push(json!({ "text": other.to_string() }));
        }
    }
    if out.is_empty() {
        out.push(json!({ "text": "" }));
    }
    out
}

/// Convert a single OpenAI Chat content part to a Gemini part. Returns `None`
/// for unrecognised types so they are silently dropped (matches the OpenAI →
/// Anthropic policy for unknown parts).
fn openai_content_part_to_gemini_part(part: &Value) -> Option<Value> {
    let part_type = part.get("type").and_then(|v| v.as_str());
    match part_type {
        // Bare strings inside a content array — treat as text.
        None | Some("text") => part
            .get("text")
            .and_then(|v| v.as_str())
            .map(|t| json!({ "text": t })),
        Some("image_url") => openai_image_url_part_to_gemini_part(part),
        _ => part
            .get("text")
            .and_then(|v| v.as_str())
            .map(|t| json!({ "text": t })),
    }
}

/// Map an OpenAI `image_url` content part to a Gemini `inlineData` (data: URI)
/// or `fileData` (HTTP URL) part. Accepts both string and object shapes for the
/// `image_url` field.
fn openai_image_url_part_to_gemini_part(part: &Value) -> Option<Value> {
    let url = part.get("image_url").and_then(|iu| match iu {
        Value::String(s) => Some(s.as_str()),
        Value::Object(o) => o.get("url").and_then(|v| v.as_str()),
        _ => None,
    })?;

    if let Some(rest) = url.strip_prefix("data:") {
        let (meta, data) = rest.split_once(',')?;
        let mime = meta
            .split(';')
            .next()
            .filter(|m| !m.is_empty())
            .unwrap_or("image/png");
        Some(json!({
            "inlineData": {
                "mimeType": mime,
                "data": data,
            }
        }))
    } else if url.starts_with("http://") || url.starts_with("https://") {
        // Best-effort mime sniff from extension; Gemini will reject if wrong
        // but most clients pair URL parts with correct extensions.
        let mime = mime_from_url(url);
        Some(json!({
            "fileData": {
                "fileUri": url,
                "mimeType": mime,
            }
        }))
    } else {
        None
    }
}

fn mime_from_url(url: &str) -> &'static str {
    let lower = url.to_ascii_lowercase();
    let path_only = lower.split(['?', '#']).next().unwrap_or(&lower);
    if path_only.ends_with(".png") {
        "image/png"
    } else if path_only.ends_with(".jpg") || path_only.ends_with(".jpeg") {
        "image/jpeg"
    } else if path_only.ends_with(".webp") {
        "image/webp"
    } else if path_only.ends_with(".gif") {
        "image/gif"
    } else if path_only.ends_with(".heic") {
        "image/heic"
    } else if path_only.ends_with(".heif") {
        "image/heif"
    } else {
        "image/jpeg"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_convert_openai_chat_to_gemini_request_with_tools() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "system", "content": "Be precise."},
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "ls", "arguments": "{\"path\":\".\"}"}
                }]},
                {"role": "tool", "tool_call_id": "call_1", "content": "{\"files\":[]}"}
            ],
            "tools": [{
                "type": "function",
                "function": {"name": "ls", "description": "list", "parameters": {"type":"object"}}
            }]
        });

        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        assert_eq!(
            converted["systemInstruction"]["parts"][0]["text"],
            "Be precise."
        );
        assert_eq!(
            converted["contents"][1]["parts"][0]["functionCall"]["name"],
            "ls"
        );
        assert_eq!(
            converted["contents"][2]["parts"][0]["functionResponse"]["name"],
            "ls"
        );
    }

    #[test]
    fn test_convert_gemini_to_openai_chat_response_with_function_call() {
        let body = json!({
            "candidates": [{
                "content": {
                    "parts": [
                        {"text": "Need tool"},
                        {"functionCall": {"id": "call_1", "name": "ls", "args": {"path":"."}}}
                    ]
                },
                "finishReason": "STOP"
            }],
            "usageMetadata": {
                "promptTokenCount": 10,
                "candidatesTokenCount": 4,
                "cachedContentTokenCount": 90
            }
        });

        let converted = convert_gemini_to_openai_chat_response(&body, "gemini-2.5-pro");
        assert_eq!(converted["choices"][0]["finish_reason"], "tool_calls");
        assert_eq!(
            converted["choices"][0]["message"]["tool_calls"][0]["id"],
            "call_1"
        );
        assert_eq!(converted["usage"]["cache_read_input_tokens"], 90);
    }

    #[test]
    fn test_build_google_stream_generate_content_url() {
        assert_eq!(
            build_google_stream_generate_content_url(
                "https://generativelanguage.googleapis.com/v1beta",
                "gemini-2.5-pro"
            ),
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:streamGenerateContent?alt=sse"
        );
        assert_eq!(
            build_google_stream_generate_content_url(
                "https://generativelanguage.googleapis.com/v1beta/models",
                "google/gemini-2.5-pro"
            ),
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:streamGenerateContent?alt=sse"
        );
        // Bare hostname without /v1beta — should auto-add /v1beta
        assert_eq!(
            build_google_stream_generate_content_url(
                "https://generativelanguage.googleapis.com",
                "gemini-2.5-flash"
            ),
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:streamGenerateContent?alt=sse"
        );
    }

    #[test]
    fn test_convert_openai_chat_empty_messages() {
        let body = json!({"model": "gemini-2.5-pro", "messages": []});
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        // Empty messages → fallback empty content injected
        let contents = converted["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 1);
        assert_eq!(contents[0]["role"], "user");
    }

    #[test]
    fn test_convert_openai_chat_missing_messages_field() {
        let body = json!({"model": "gemini-2.5-pro"});
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        // No messages at all → fallback empty content
        let contents = converted["contents"].as_array().unwrap();
        assert!(!contents.is_empty());
    }

    #[test]
    fn test_convert_openai_chat_null_content_no_panic() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": null}]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        assert!(converted["contents"].is_array());
    }

    #[test]
    fn test_convert_gemini_response_empty_candidates() {
        let resp = json!({"candidates": []});
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini-2.5-pro");
        assert_eq!(converted["choices"][0]["finish_reason"], "stop");
    }

    #[test]
    fn test_convert_gemini_response_no_candidates_field() {
        let resp = json!({});
        let converted = convert_gemini_to_openai_chat_response(&resp, "fallback-model");
        assert_eq!(converted["model"], "fallback-model");
        assert_eq!(converted["choices"][0]["finish_reason"], "stop");
        assert_eq!(converted["usage"]["prompt_tokens"], 0);
    }

    #[test]
    fn test_convert_gemini_response_safety_finish_reason() {
        let resp = json!({
            "candidates": [{"content": {"parts": []}, "finishReason": "SAFETY"}]
        });
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini");
        assert_eq!(converted["choices"][0]["finish_reason"], "content_filter");
    }

    #[test]
    fn test_convert_gemini_response_recitation_finish_reason() {
        // RECITATION = blocked due to verbatim training-data quote. Should map
        // to OpenAI content_filter (same family as SAFETY) rather than collapse
        // to "stop" via the catch-all arm.
        let resp = json!({
            "candidates": [{"content": {"parts": []}, "finishReason": "RECITATION"}]
        });
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini");
        assert_eq!(converted["choices"][0]["finish_reason"], "content_filter");
    }

    #[test]
    fn test_openai_chat_model_missing_uses_default() {
        let body = json!({});
        assert_eq!(openai_chat_model(&body, "default-model"), "default-model");
    }

    #[test]
    fn test_build_google_url_trailing_slash() {
        let url =
            build_google_generate_content_url("https://example.com/v1beta/", "gemini-2.5-pro");
        assert!(url.contains("models/gemini-2.5-pro:generateContent"));
        assert!(!url.contains("//models"));
    }

    #[test]
    fn test_parse_tool_content_none() {
        assert_eq!(parse_tool_content(None), json!({}));
    }

    #[test]
    fn test_parse_tool_content_non_json_string() {
        let content = json!("not valid json");
        assert_eq!(
            parse_tool_content(Some(&content)),
            json!({"content": "not valid json"})
        );
    }

    #[test]
    fn convert_openai_to_gemini_invalid_tool_args_json() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "do_stuff", "arguments": "not json"}
                }]}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        // Invalid JSON arguments should fall back to {}
        let fc = &converted["contents"][1]["parts"][0]["functionCall"];
        assert_eq!(fc["name"], "do_stuff");
        assert_eq!(fc["args"], json!({}));
    }

    #[test]
    fn convert_gemini_to_openai_null_function_call_args() {
        // Missing args field entirely → defaults to {}
        let resp_missing = json!({
            "candidates": [{
                "content": {
                    "parts": [
                        {"functionCall": {"name": "do_stuff"}}
                    ]
                },
                "finishReason": "STOP"
            }]
        });
        let converted = convert_gemini_to_openai_chat_response(&resp_missing, "gemini-2.5-pro");
        let tool_call = &converted["choices"][0]["message"]["tool_calls"][0];
        assert_eq!(tool_call["function"]["name"], "do_stuff");
        let args: Value =
            serde_json::from_str(tool_call["function"]["arguments"].as_str().unwrap()).unwrap();
        assert_eq!(args, json!({}));

        // Explicit null args → serialized as "null", doesn't panic
        let resp_null = json!({
            "candidates": [{
                "content": {
                    "parts": [
                        {"functionCall": {"name": "do_stuff", "args": null}}
                    ]
                },
                "finishReason": "STOP"
            }]
        });
        let converted_null = convert_gemini_to_openai_chat_response(&resp_null, "gemini-2.5-pro");
        let tool_call_null = &converted_null["choices"][0]["message"]["tool_calls"][0];
        assert_eq!(tool_call_null["function"]["name"], "do_stuff");
        assert!(tool_call_null["function"]["arguments"].as_str().is_some());
    }

    #[test]
    fn convert_gemini_to_openai_max_tokens_finish_reason() {
        let resp = json!({
            "candidates": [{
                "content": {"parts": [{"text": "truncated output"}]},
                "finishReason": "MAX_TOKENS"
            }]
        });
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini-2.5-pro");
        assert_eq!(converted["choices"][0]["finish_reason"], "length");
    }

    #[test]
    fn convert_gemini_to_openai_null_usage_metadata() {
        let resp = json!({
            "candidates": [{
                "content": {"parts": [{"text": "hi"}]},
                "finishReason": "STOP"
            }],
            "usageMetadata": {
                "promptTokenCount": null,
                "candidatesTokenCount": null
            }
        });
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini-2.5-pro");
        assert_eq!(converted["usage"]["prompt_tokens"], 0);
        assert_eq!(converted["usage"]["completion_tokens"], 0);
        assert_eq!(converted["usage"]["total_tokens"], 0);
    }

    #[test]
    fn convert_gemini_to_openai_missing_function_call_id() {
        let resp = json!({
            "candidates": [{
                "content": {
                    "parts": [
                        {"functionCall": {"name": "my_func", "args": {"key": "val"}}}
                    ]
                },
                "finishReason": "STOP"
            }]
        });
        let converted = convert_gemini_to_openai_chat_response(&resp, "gemini-2.5-pro");
        let tool_call = &converted["choices"][0]["message"]["tool_calls"][0];
        // Missing id should generate a synthetic one like "call_0"
        assert_eq!(tool_call["id"], "call_0");
        assert_eq!(tool_call["function"]["name"], "my_func");
    }

    #[test]
    fn parse_tool_content_json_object_passthrough() {
        let content = json!("{\"result\": 42, \"status\": \"ok\"}");
        let parsed = parse_tool_content(Some(&content));
        // Valid JSON object string should be parsed, not double-wrapped
        assert_eq!(parsed["result"], 42);
        assert_eq!(parsed["status"], "ok");
        assert!(parsed.get("content").is_none());
    }

    #[test]
    fn convert_openai_to_gemini_tool_choice_specific_function() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "call X"}],
            "tools": [{
                "type": "function",
                "function": {"name": "X", "description": "do X", "parameters": {"type": "object"}}
            }],
            "tool_choice": {
                "type": "function",
                "function": {"name": "X"}
            }
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let fc_config = &converted["toolConfig"]["functionCallingConfig"];
        assert_eq!(fc_config["mode"], "ANY");
        assert_eq!(fc_config["allowedFunctionNames"][0], "X");
    }

    #[test]
    fn convert_openai_to_gemini_empty_string_arguments() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "do_stuff", "arguments": ""}
                }]}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        // Empty string arguments should fall back to {}
        let fc = &converted["contents"][1]["parts"][0]["functionCall"];
        assert_eq!(fc["name"], "do_stuff");
        assert_eq!(fc["args"], json!({}));
    }

    #[test]
    fn convert_openai_to_gemini_tool_result_without_prior_assistant_call() {
        // When tool result references a call_id not in conversation history,
        // the function name should fall back to the call_id itself
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "tool", "tool_call_id": "call_abc123", "content": "{\"result\": 42}"}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let fr = &converted["contents"][1]["parts"][0]["functionResponse"];
        // Should use call_id as fallback name, not empty string
        assert_eq!(fr["name"], "call_abc123");
    }

    #[test]
    fn convert_openai_to_gemini_groups_parallel_tool_results_into_one_user_turn() {
        let body = json!({
            "model": "gemini-3-flash-preview",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [
                    {
                        "id": "call_1",
                        "type": "function",
                        "function": {"name": "read_file", "arguments": "{\"path\":\"a.txt\"}"}
                    },
                    {
                        "id": "call_2",
                        "type": "function",
                        "function": {"name": "write_file", "arguments": "{\"path\":\"b.txt\"}"}
                    }
                ]},
                {"role": "tool", "tool_call_id": "call_1", "content": "{\"ok\":1}"},
                {"role": "tool", "tool_call_id": "call_2", "content": "{\"ok\":2}"},
                {"role": "user", "content": "next"}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        let contents = converted["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 4);
        assert_eq!(contents[2]["role"], "user");
        let parts = contents[2]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0]["functionResponse"]["id"], "call_1");
        assert_eq!(parts[0]["functionResponse"]["name"], "read_file");
        assert_eq!(parts[1]["functionResponse"]["id"], "call_2");
        assert_eq!(parts[1]["functionResponse"]["name"], "write_file");
    }

    #[test]
    fn convert_openai_to_gemini_single_tool_result_produces_one_user_turn() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "read_file", "arguments": "{}"}
                }]},
                {"role": "tool", "tool_call_id": "call_1", "content": "{\"ok\":1}"},
                {"role": "user", "content": "next"}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        let contents = converted["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 4);
        assert_eq!(contents[2]["role"], "user");
        let parts = contents[2]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 1);
        assert_eq!(parts[0]["functionResponse"]["id"], "call_1");
        assert_eq!(parts[0]["functionResponse"]["name"], "read_file");
        assert_eq!(contents[3]["role"], "user");
        assert_eq!(contents[3]["parts"][0]["text"], "next");
    }

    #[test]
    fn convert_openai_to_gemini_groups_tool_results_without_prior_assistant_call() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "tool", "tool_call_id": "call_a", "content": "{\"r\":1}"},
                {"role": "tool", "tool_call_id": "call_b", "content": "{\"r\":2}"}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        let contents = converted["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 2);
        assert_eq!(contents[1]["role"], "user");
        let parts = contents[1]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0]["functionResponse"]["id"], "call_a");
        assert_eq!(parts[0]["functionResponse"]["name"], "call_a");
        assert_eq!(parts[1]["functionResponse"]["id"], "call_b");
        assert_eq!(parts[1]["functionResponse"]["name"], "call_b");
    }

    #[test]
    fn convert_openai_to_gemini_tool_groups_separated_by_assistant_do_not_merge() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [
                {"role": "user", "content": "hi"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_1",
                    "type": "function",
                    "function": {"name": "read_file", "arguments": "{}"}
                }]},
                {"role": "tool", "tool_call_id": "call_1", "content": "{\"ok\":1}"},
                {"role": "assistant", "tool_calls": [{
                    "id": "call_2",
                    "type": "function",
                    "function": {"name": "write_file", "arguments": "{}"}
                }]},
                {"role": "tool", "tool_call_id": "call_2", "content": "{\"ok\":2}"}
            ]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        let contents = converted["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 5);
        assert_eq!(contents[2]["role"], "user");
        assert_eq!(contents[2]["parts"].as_array().unwrap().len(), 1);
        assert_eq!(
            contents[2]["parts"][0]["functionResponse"]["name"],
            "read_file"
        );
        assert_eq!(contents[4]["role"], "user");
        assert_eq!(contents[4]["parts"].as_array().unwrap().len(), 1);
        assert_eq!(
            contents[4]["parts"][0]["functionResponse"]["name"],
            "write_file"
        );
    }

    #[test]
    fn convert_openai_to_gemini_tool_choice_none() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "hi"}],
            "tools": [{
                "type": "function",
                "function": {"name": "ls", "description": "list", "parameters": {"type": "object"}}
            }],
            "tool_choice": "none"
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let fc_config = &converted["toolConfig"]["functionCallingConfig"];
        assert_eq!(fc_config["mode"], "NONE");
    }

    #[test]
    fn sanitize_schema_strips_unsupported_fields() {
        let schema = json!({
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "description": "file path",
                    "additionalProperties": false,
                    "default": "/tmp"
                },
                "options": {
                    "type": "object",
                    "properties": {
                        "recursive": {"type": "boolean", "$ref": "#/defs/x"}
                    },
                    "additionalProperties": false,
                    "propertyNames": {"pattern": "^[a-z]+$"}
                }
            },
            "required": ["path"],
            "additionalProperties": false,
            "propertyNames": {"pattern": ".*"}
        });

        let sanitized = sanitize_schema_for_gemini(&schema);
        let obj = sanitized.as_object().unwrap();

        // Allowed fields kept
        assert_eq!(obj["type"], "object");
        assert!(obj.contains_key("properties"));
        assert!(obj.contains_key("required"));

        // Unsupported fields stripped at top level
        assert!(!obj.contains_key("$schema"));
        assert!(!obj.contains_key("additionalProperties"));
        assert!(!obj.contains_key("propertyNames"));

        // Unsupported fields stripped in nested properties
        let path_prop = &obj["properties"]["path"];
        assert!(
            !path_prop
                .as_object()
                .unwrap()
                .contains_key("additionalProperties")
        );
        assert!(!path_prop.as_object().unwrap().contains_key("default"));

        let options_prop = &obj["properties"]["options"];
        assert!(
            !options_prop
                .as_object()
                .unwrap()
                .contains_key("additionalProperties")
        );
        assert!(
            !options_prop
                .as_object()
                .unwrap()
                .contains_key("propertyNames")
        );

        // Nested nested property also cleaned
        let recursive = &options_prop["properties"]["recursive"];
        assert!(!recursive.as_object().unwrap().contains_key("$ref"));
    }

    #[test]
    fn gemini_signature_only_attaches_to_first_tool_call_per_turn() {
        // Gemini's signature model is per-turn — only the first part of an
        // assistant turn carries it. Match the pattern continuedev established
        // (https://github.com/continuedev/continue/pull/8865): index==0 gets a
        // signature, later parallel calls in the same turn get nothing.
        let body = json!({
            "model": "gemini-3-flash-preview",
            "messages": [
                {"role": "user", "content": "hi"},
                {
                    "role": "assistant",
                    "tool_calls": [
                        {"id": "a", "type": "function", "function": {"name": "T1", "arguments": "{}"}},
                        {"id": "b", "type": "function", "function": {"name": "T2", "arguments": "{}"}}
                    ]
                },
                {"role": "tool", "tool_call_id": "a", "content": "ok"},
                {"role": "tool", "tool_call_id": "b", "content": "ok"},
                {"role": "user", "content": "next"}
            ]
        });
        let request = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let model_part = request["contents"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["role"] == "model")
            .unwrap();
        let parts = model_part["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 2);
        assert!(
            parts[0]
                .as_object()
                .unwrap()
                .contains_key("thoughtSignature"),
            "first tool_call must carry signature"
        );
        assert!(
            !parts[1]
                .as_object()
                .unwrap()
                .contains_key("thoughtSignature"),
            "second tool_call must not carry signature (per-turn model)"
        );
    }

    #[test]
    fn gemini_signature_falls_back_to_documented_placeholder_on_cache_miss() {
        // When the cache doesn't have a signature for a call_id (e.g. process
        // restart, history aivo never saw, or a tool_call_id from a different
        // session), use Google's documented placeholder so gemini-3 doesn't
        // 400 on missing thought_signature.
        // https://ai.google.dev/gemini-api/docs/thought-signatures FAQ.
        let body = json!({
            "model": "gemini-3-flash-preview",
            "messages": [
                {"role": "user", "content": "hi"},
                {
                    "role": "assistant",
                    "tool_calls": [{
                        "id": "never_seen_id_xyz",
                        "type": "function",
                        "function": {"name": "Bash", "arguments": "{}"}
                    }]
                },
                {"role": "tool", "tool_call_id": "never_seen_id_xyz", "content": "ok"},
                {"role": "user", "content": "next"}
            ]
        });
        let request = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let model_part = request["contents"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["role"] == "model")
            .unwrap();
        assert_eq!(
            model_part["parts"][0]["thoughtSignature"],
            SKIP_THOUGHT_SIGNATURE_PLACEHOLDER
        );
    }

    #[test]
    fn gemini_signature_round_trips_through_call_id_cache() {
        // Gemini-3 returns `thoughtSignature` on functionCall response parts
        // and *requires* the same signature echoed back on subsequent turns.
        // Claude Code (the upstream client) drops unknown fields on tool blocks,
        // so we maintain a process-local cache keyed by tool_call_id and
        // re-attach signatures when the request flows back.
        let gemini_response = json!({
            "candidates": [{
                "content": {
                    "parts": [{
                        "functionCall": {
                            "name": "Skill",
                            "args": {"skill": "x"},
                            "id": "abc123"
                        },
                        "thoughtSignature": "SIG_XYZ"
                    }]
                }
            }]
        });
        // Step 1: response converter must capture the signature.
        let _ = convert_gemini_to_openai_chat_response(&gemini_response, "gemini-3-flash-preview");

        // Step 2: subsequent request whose history echoes the same call must
        // re-attach the signature on the corresponding gemini part.
        let openai_followup = json!({
            "model": "gemini-3-flash-preview",
            "messages": [
                {"role": "user", "content": "hi"},
                {
                    "role": "assistant",
                    "tool_calls": [{
                        "id": "abc123",
                        "type": "function",
                        "function": {"name": "Skill", "arguments": "{\"skill\":\"x\"}"}
                    }]
                },
                {
                    "role": "tool",
                    "tool_call_id": "abc123",
                    "content": "done"
                },
                {"role": "user", "content": "next"}
            ]
        });
        let gemini_request = convert_openai_chat_to_gemini_request(
            &openai_followup,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        // Find the model-role part with the functionCall and assert the
        // signature was attached as a sibling of functionCall (Gemini's shape).
        let model_part = gemini_request["contents"]
            .as_array()
            .unwrap()
            .iter()
            .find(|c| c["role"] == "model")
            .expect("model role should be present in contents");
        let part = &model_part["parts"][0];
        assert_eq!(part["functionCall"]["id"], "abc123");
        assert_eq!(
            part["thoughtSignature"], "SIG_XYZ",
            "thoughtSignature must be re-attached from cache by call_id"
        );
    }

    #[test]
    fn sanitize_schema_anyof_strips_sibling_schema_fields() {
        // Gemini API returns 400 INVALID_ARGUMENT when `anyOf` appears alongside
        // sibling schema-defining fields like `type`, `properties`, `required`:
        //   "When using any_of, it must be the only field set."
        // This is what breaks Claude Code's `SendMessage` tool through aivo's
        // anthropic→gemini bridge.
        let schema = json!({
            "anyOf": [
                {"type": "string", "description": "string form"},
                {"type": "object", "properties": {"foo": {"type": "string"}}}
            ],
            "properties": {},
            "type": "object",
            "required": ["x"],
            "description": "union value"
        });
        let sanitized = sanitize_schema_for_gemini(&schema);
        let obj = sanitized.as_object().unwrap();
        assert!(obj.contains_key("anyOf"), "anyOf must be preserved");
        assert!(
            !obj.contains_key("type"),
            "type must be stripped when anyOf is set"
        );
        assert!(
            !obj.contains_key("properties"),
            "properties must be stripped when anyOf is set"
        );
        assert!(
            !obj.contains_key("required"),
            "required must be stripped when anyOf is set"
        );
    }

    #[test]
    fn sanitize_schema_anyof_recursively_strips_inside_variants() {
        // The Claude Code SendMessage tool nests anyOf inside an anyOf variant —
        // the inner variant also has type+properties+anyOf together. Same fix
        // must apply at every depth.
        let schema = json!({
            "anyOf": [
                {"type": "string"},
                {
                    "anyOf": [{"type": "string"}, {"type": "number"}],
                    "type": "object",
                    "properties": {}
                }
            ]
        });
        let sanitized = sanitize_schema_for_gemini(&schema);
        let inner = &sanitized["anyOf"][1];
        let inner_obj = inner.as_object().unwrap();
        assert!(inner_obj.contains_key("anyOf"));
        assert!(
            !inner_obj.contains_key("type"),
            "nested anyOf variant must also drop sibling type"
        );
        assert!(
            !inner_obj.contains_key("properties"),
            "nested anyOf variant must also drop sibling properties"
        );
    }

    #[test]
    fn sanitize_schema_preserves_valid_fields() {
        let schema = json!({
            "type": "object",
            "description": "parameters",
            "properties": {
                "count": {
                    "type": "integer",
                    "description": "item count",
                    "minimum": 0,
                    "maximum": 100
                },
                "tags": {
                    "type": "array",
                    "items": {"type": "string", "enum": ["a", "b"]},
                    "minItems": 1,
                    "maxItems": 10
                }
            },
            "required": ["count"]
        });

        let sanitized = sanitize_schema_for_gemini(&schema);
        assert_eq!(sanitized["properties"]["count"]["minimum"], 0);
        assert_eq!(sanitized["properties"]["count"]["maximum"], 100);
        assert_eq!(sanitized["properties"]["tags"]["items"]["enum"][0], "a");
        assert_eq!(sanitized["properties"]["tags"]["minItems"], 1);
    }

    #[test]
    fn convert_openai_to_gemini_sanitizes_tool_parameters() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "hi"}],
            "tools": [{
                "type": "function",
                "function": {
                    "name": "read_file",
                    "description": "Read a file",
                    "parameters": {
                        "$schema": "http://json-schema.org/draft-07/schema#",
                        "type": "object",
                        "properties": {
                            "path": {"type": "string", "additionalProperties": false}
                        },
                        "required": ["path"],
                        "additionalProperties": false,
                        "propertyNames": {"pattern": ".*"}
                    }
                }
            }]
        });

        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );

        let params = &converted["tools"][0]["functionDeclarations"][0]["parameters"];
        let obj = params.as_object().unwrap();
        assert!(!obj.contains_key("$schema"));
        assert!(!obj.contains_key("additionalProperties"));
        assert!(!obj.contains_key("propertyNames"));
        assert_eq!(obj["type"], "object");
        assert!(obj.contains_key("properties"));
    }

    #[test]
    fn convert_openai_to_gemini_image_url_data_uri_becomes_inline_data() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{
                "role": "user",
                "content": [
                    {"type": "text", "text": "what is this?"},
                    {"type": "image_url", "image_url": {
                        "url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
                    }}
                ]
            }]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let parts = converted["contents"][0]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 2);
        assert_eq!(parts[0]["text"], "what is this?");
        assert_eq!(parts[1]["inlineData"]["mimeType"], "image/png");
        assert!(
            parts[1]["inlineData"]["data"]
                .as_str()
                .unwrap()
                .starts_with("iVBORw0KGgo")
        );
    }

    #[test]
    fn convert_openai_to_gemini_image_url_http_becomes_file_data() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": "https://example.com/cat.jpg"}}
                ]
            }]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let parts = converted["contents"][0]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 1);
        assert_eq!(
            parts[0]["fileData"]["fileUri"],
            "https://example.com/cat.jpg"
        );
        assert_eq!(parts[0]["fileData"]["mimeType"], "image/jpeg");
    }

    #[test]
    fn convert_openai_to_gemini_forwards_top_k_seed_response_format_and_stop() {
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "hi"}],
            "top_k": 32,
            "seed": 7,
            "response_format": {"type": "json_object"},
            "stop": ["END"]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let g = &converted["generationConfig"];
        assert_eq!(g["topK"], 32);
        assert_eq!(g["seed"], 7);
        assert_eq!(g["responseMimeType"], "application/json");
        assert_eq!(g["stopSequences"][0], "END");
    }

    #[test]
    fn convert_openai_to_gemini_drops_unsupported_response_format_types() {
        // json_schema is not converted (yet); ensure we don't accidentally
        // emit responseMimeType on shapes we haven't validated.
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "hi"}],
            "response_format": {"type": "json_schema", "json_schema": {}}
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        assert!(
            converted
                .get("generationConfig")
                .and_then(|g| g.get("responseMimeType"))
                .is_none(),
            "json_schema response_format should not produce responseMimeType"
        );
    }

    #[test]
    fn signature_cache_is_keyed_by_model_to_prevent_cross_model_contamination() {
        // A signature captured against gemini-2.5-pro must NOT be replayed
        // against gemini-3-flash-preview — the two models use different
        // signature schemas and a stale 2.5 signature triggers a 400 on 3.x.
        let call_id = "test_xmodel_iso_call_a";
        super::remember_signature("gemini-2.5-pro", call_id, "sig-25");
        super::remember_signature("gemini-3-flash-preview", call_id, "sig-30");

        assert_eq!(
            super::lookup_signature("gemini-2.5-pro", call_id).as_deref(),
            Some("sig-25")
        );
        assert_eq!(
            super::lookup_signature("gemini-3-flash-preview", call_id).as_deref(),
            Some("sig-30")
        );
        // A model name we never wrote to should miss.
        assert_eq!(
            super::lookup_signature("gemini-3-pro-preview", call_id),
            None
        );
    }

    #[test]
    fn signature_cache_key_combines_model_and_call_id() {
        assert_eq!(
            super::cache_key("gemini-3-flash-preview", "call_42"),
            "gemini-3-flash-preview|call_42"
        );
    }

    #[test]
    fn signature_cache_prune_drops_entries_older_than_ttl() {
        let mut map = HashMap::new();
        let now: u64 = 1_000_000;
        map.insert(
            "fresh".to_string(),
            super::SignatureEntry {
                signature: "ok".to_string(),
                captured_at: now - 60, // 1 minute ago
            },
        );
        map.insert(
            "stale".to_string(),
            super::SignatureEntry {
                signature: "old".to_string(),
                captured_at: now - super::SIGNATURE_TTL_SECS - 1, // expired
            },
        );
        super::prune_expired(&mut map, now);
        assert!(map.contains_key("fresh"));
        assert!(!map.contains_key("stale"));
    }

    #[test]
    fn signature_capture_handles_part_signature_without_function_call() {
        // gemini-3-pro-image-preview attaches thoughtSignature to the FIRST
        // model-emitted part (text or inlineData) of a step. When a sibling
        // tool call follows, the signature should still be associated with
        // the call_id so the next turn can echo it back.
        let call_id = "test_leading_part_sig_call_b";
        let resp = json!({
            "candidates": [{
                "content": {
                    "parts": [
                        {"text": "thinking…", "thoughtSignature": "SIG_LEADING"},
                        {
                            "functionCall": {
                                "id": call_id,
                                "name": "search",
                                "args": {"q": "x"}
                            }
                        }
                    ]
                }
            }]
        });
        let _ = convert_gemini_to_openai_chat_response(&resp, "gemini-3-pro-image-preview");
        assert_eq!(
            super::lookup_signature("gemini-3-pro-image-preview", call_id).as_deref(),
            Some("SIG_LEADING"),
            "leading-part signature must be carried over to the sibling tool call"
        );
    }

    #[test]
    fn write_string_atomic_round_trips_json() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sigs.json");
        let payload = serde_json::json!({
            "call_a": "sig-a",
            "call_b": "sig-b"
        })
        .to_string();
        super::write_string_atomic(&path, &payload);
        let read_back = std::fs::read_to_string(&path).unwrap();
        let parsed: HashMap<String, String> = serde_json::from_str(&read_back).unwrap();
        assert_eq!(parsed.get("call_a").map(String::as_str), Some("sig-a"));
        assert_eq!(parsed.get("call_b").map(String::as_str), Some("sig-b"));
    }

    #[test]
    fn write_string_atomic_overwrites_existing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("sigs.json");
        super::write_string_atomic(&path, "{\"x\":\"1\"}");
        super::write_string_atomic(&path, "{\"x\":\"2\"}");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "{\"x\":\"2\"}");
    }

    #[test]
    fn openai_reasoning_effort_high_maps_to_gemini_thinking_level() {
        let body = json!({
            "model": "gemini-3-pro-preview",
            "messages": [{"role": "user", "content": "hi"}],
            "reasoning_effort": "high"
        });
        let req = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-3-pro-preview",
            },
        );
        assert_eq!(
            req["generationConfig"]["thinkingConfig"]["thinking_level"],
            "high"
        );
    }

    #[test]
    fn openai_reasoning_effort_minimal_omits_gemini_thinking_config() {
        let body = json!({
            "model": "gemini-3-pro-preview",
            "messages": [{"role": "user", "content": "hi"}],
            "reasoning_effort": "minimal"
        });
        let req = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-3-pro-preview",
            },
        );
        assert!(
            req["generationConfig"]
                .as_object()
                .map(|m| !m.contains_key("thinkingConfig"))
                .unwrap_or(true)
        );
    }

    #[test]
    fn convert_openai_to_gemini_text_only_unchanged() {
        // Regression: pure-text input still produces a single text part.
        let body = json!({
            "model": "gemini-2.5-pro",
            "messages": [{"role": "user", "content": "hi"}]
        });
        let converted = convert_openai_chat_to_gemini_request(
            &body,
            &OpenAIToGeminiConfig {
                default_model: "gemini-2.5-pro",
            },
        );
        let parts = converted["contents"][0]["parts"].as_array().unwrap();
        assert_eq!(parts.len(), 1);
        assert_eq!(parts[0]["text"], "hi");
    }
}
